%BRAPH 2 for DiSTAP.

braph2

if ispc
    fprintf([ ...
        '\n' ...
        '<strong>ØØØØ       ØØØØ ØØØØØ  ØØØ  ØØØØ    @@@@  @ @@@@  @@@@ @    @ @   @ @@@@  @@@@\n</strong>' ...
        '<strong>Ø   Ø  Ø  Ø       Ø   Ø   Ø Ø   Ø   @   @ @ @   @ @    @    @ @@  @ @    @    \n</strong>' ...
        '<strong>Ø   Ø      ØØØ    Ø   ØØØØØ ØØØØ    @@@@  @ @@@@  @@@  @    @ @ @ @ @@@   @@@ \n</strong>' ...
        '<strong>Ø   Ø  Ø      Ø   Ø   Ø   Ø Ø       @     @ @     @    @    @ @  @@ @        @\n</strong>' ...
        '<strong>ØØØØ   Ø  ØØØØ    Ø   Ø   Ø Ø       @     @ @     @@@@ @@@@ @ @   @ @@@@ @@@@ \n</strong>' ...
        '\n' ...
        ]);
else
    fprintf([ ...
        '\n' ...
        ' ████       ████ █████  ███  ████    ▒▒▒▒  ▒ ▒▒▒▒  ▒▒▒▒ ▒    ▒ ▒   ▒ ▒▒▒▒  ▒▒▒▒\n' ...
        ' █   █  █  █       █   █   █ █   █   ▒   ▒ ▒ ▒   ▒ ▒    ▒    ▒ ▒▒  ▒ ▒    ▒    \n' ...
        ' █   █      ███    █   █████ ████    ▒▒▒▒  ▒ ▒▒▒▒  ▒▒▒  ▒    ▒ ▒ ▒ ▒ ▒▒▒   ▒▒▒ \n' ...
        ' █   █  █      █   █   █   █ █       ▒     ▒ ▒     ▒    ▒    ▒ ▒  ▒▒ ▒        ▒\n' ...
        ' ████   █  ████    █   █   █ █       ▒     ▒ ▒     ▒▒▒▒ ▒▒▒▒ ▒ ▒   ▒ ▒▒▒▒ ▒▒▒▒ \n' ...
        '\n' ...
        ]);
end

fprintf([ ...
    '\n' ...
    ' <a href="matlab:pip = ImporterPipelineBRAPH2(''FILE'', [fileparts(which(''RamanExperiment'')) filesep ''pipeline_load_raman_ASC.braph2''], ''WAITBAR'', true).get(''PIP''); gui = GUIElement(''PE'', pip, ''WAITBAR'', true); gui.get(''DRAW''); gui.get(''SHOW'');">Load Raman from ASC files</a>\n' ...
    ' <a href="matlab:pip = ImporterPipelineBRAPH2(''FILE'', [fileparts(which(''RamanExperiment'')) filesep ''pipeline_load_raman_TXT.braph2''], ''WAITBAR'', true).get(''PIP''); gui = GUIElement(''PE'', pip, ''WAITBAR'', true); gui.get(''DRAW''); gui.get(''SHOW'');">Load Raman from TXT files</a>\n' ...
    '\n' ...
    ])